### PR TITLE
Replace REQUIRE file with Project.toml

### PR DESCRIPTION
**Pull request by nickrobinson251**
Hello, @Tchanders -- thanks for your work on this package. I'd be interested in contributing. Thought adding a Project.toml would help with releasing newer versions of the package. This intial version should match exactly the information from the REQUIRE and [Registry](https://github.com/JuliaRegistries/General/tree/master/I/InformationMeasures).

### CODE REVIEW

**Comment by nickrobinson251** [comment]
Bump :)

**Comment by Tchanders** [comment]
@nickrobinson251 Thanks for looking into this. I'm still getting up to speed on Pkg.jl - looks like we need a Maniphest.toml too?

**Comment by nickrobinson251** [comment]
For packages, a `Project.toml` is usually sufficient.

A `Manifest.toml` file records all the exact versions of dependendies (even indirect dependencies) that were present in a particular environment. This is useful for making sure e.g. the result of running a script can be reproduced. It is less useful for a package, where we merely want to declare compatibility bounds for dependencies, which is what the `Project.toml` does. 

https://julialang.github.io/Pkg.jl/v1/toml-files/

**Comment by Tchanders** [comment]
Thanks @nickrobinson251!

**Pull request merged**
